services:
  mongo:
    image: mongo:7
    container_name: digitalnest-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - digitalnest-mongo-data:/data/db

volumes:
  digitalnest-mongo-data:
